server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: notification-service
  cloud:
    config:
      enabled: false          # local testing: Config Server band
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: notification-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info