server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}
payment:
  commission-rate: 0.15
management:
  endpoints:
    web:
      exposure:
        include: health,info
